### ISSUE TITLE
add social media icons in the footer

### ISSUE THREAD

**Issue by Aryakhot** [shivamyadavrgipt/Social_media_management#111]
adding social media icons in the footer makes your website look more professional and makes the users trust you. since this website is about social media management, adding such icons will be a good idea. 
please assign me this task.

**Comment by shivamyadavrgipt** [comment]
@Aryakhot also do put links of respective social media account .so that on clicking redirected towards the account

**Comment by Aryakhot** [comment]
okay sure!
