### ISSUE TITLE
Google translator

### ISSUE THREAD

**Issue by Sawan-Kushwah** [shivamyadavrgipt/Social_media_management#114]
It will change the language of whole website as we know in India even in world there are many language and our user can be from any place and some user doesn't understand english so it will be better if we provide them the content of our website in there native language

![Screenshot 2024-10-17 140930](https://github.com/user-attachments/assets/2132b82d-5f33-4136-ac18-84395943d917)

Please assign me i can work on this Default is english but user has a button on clicking he get option of language and we could select form that

**Comment by shivamyadavrgipt** [comment]
@Sawan-Kushwah this was raised earlier
