### ISSUE TITLE
Improve Landing Page 

### ISSUE THREAD

**Issue by dev129** [shivamyadavrgipt/Social_media_management#125]
Hi @shivamyadavrgipt,

I’ve noticed that the landing page of your site could be more visually appealing, and I believe I can make it look much better. Additionally, the arrangement of the FAQ section and the Chatbot isn't optimized, which affects the overall user experience.

If you assign this task to me, I can enhance the design and fix these issues within 24 hours of approval. Let me know if you're interested!

**Comment by shivamyadavrgipt** [comment]
@dev129 assigned

**Comment by dev129** [comment]
Hi @shivamyadavrgipt  please also assign the level and hacktoberfest label too.

**Comment by dev129** [comment]
Hi @shivamyadavrgipt 
The structure is not well defined, proper arrangement is not present, I am sorry I can't continue with this, I atleast need level 3 , and structure the whole navbar according to the one of homepage and then create the error 404 page.
