### ISSUE TITLE
creating login and signup page

### ISSUE THREAD

**Issue by keshav2025** [shivamyadavrgipt/Social_media_management#133]
![Screenshot 2024-10-21 at 12 26 49 PM](https://github.com/user-attachments/assets/1b9ec47f-0a82-4f4b-b706-4621f8f5052c)
![Screenshot 2024-10-21 at 12 26 35 PM](https://github.com/user-attachments/assets/40c8e91f-d94e-421e-9459-c98a2d3a95c5)

**Comment by GadagiPooja** [comment]
Hello,
I can work on this issue please assign it to me.

**Comment by keshav2025** [comment]
> Hello, I can work on this issue please assign it to me.

ok

**Comment by shivamyadavrgipt** [comment]
@GadagiPooja already raised
