### ISSUE TITLE
Fixing of Issue of Login and signup page and adding User authentication

### ISSUE THREAD

**Issue by priyachau12** [shivamyadavrgipt/Social_media_management#149]
Landing Page navbar alignment issue
![image](https://github.com/user-attachments/assets/0bb97c85-681f-4d3b-8dc9-d8d17515335b)

Sign up page is not working
![image](https://github.com/user-attachments/assets/ea3f03c2-2e2c-4c3c-bb83-0fa6778761eb)

There is no Login page
![image](https://github.com/user-attachments/assets/61fae1a2-88e4-4768-9d1d-c8b667552865)

**Comment by priyachau12** [comment]
Description: We are experiencing multiple issues with the user authentication process and the landing page's navigation.

1. User Authentication Issues:

Signup Page: The signup functionality is currently non-operational. Users are unable to create new accounts due to [specify the exact error or behavior, if known, e.g., form submission failure, error messages, etc.].
Login Page: There is no dedicated login page available, which prevents users from accessing their accounts. This needs to be implemented as part of the user authentication flow.
2. Navbar Alignment Issue:

The navbar on the landing page has alignment issues. It appears [describe the alignment problem, e.g., off-center, overlapping elements, etc.], which negatively affects the user interface and experience.
Acceptance Criteria:

The signup page should function correctly, allowing users to create accounts without errors.
A login page should be created, enabling users to authenticate their accounts.
The navbar should be properly aligned and visually appealing on the landing page.
Steps to Reproduce:

Navigate to the landing page.
Attempt to access the signup page.
Observe the failure to create an account.
Note the absence of a login page.
Examine the navbar for alignment issues.
Expected Result:

Users should be able to successfully sign up and log in to their accounts.
The navbar should be correctly aligned and functional.
Priority: High

**Comment by shivamyadavrgipt** [comment]
@priyachau12 assigned

**Comment by NK-Works** [comment]
@shivanjalikarande its been a week with no response if you want i can work on it as I have already resolved most of the conflicts during my work on the settings page

**Comment by NK-Works** [comment]
@shivamyadavrgipt there is still errors in the login and signup page i can fix it shall i create a new isssue
