### ISSUE TITLE
Added quick feedback button in separate file

### ISSUE THREAD

**Issue by prashu2507** [shivamyadavrgipt/Social_media_management#154]
Title: Added Quick Feedback Button in Separate File

Description: This PR introduces a quick feedback feature to the project. The feedback button and form are encapsulated within a new file, feedback.html, to keep the code modular and easy to maintain. Here’s a summary of the changes:

Created a new file, feedback.html, containing the HTML, CSS, and JavaScript for a feedback button and modal form.
Added a link to feedback.html from the main page (e.g., in index.html), allowing users to access the feedback feature.
The feedback modal includes a text area for users to input their feedback and a submit button that triggers a thank-you alert.
Linked Issue: Closes <152>

**Comment by shivamyadavrgipt** [comment]
@prashu2507 already raised #152
