### ISSUE TITLE
Navbar is not responsive let me work on and fix it

### ISSUE THREAD

**Issue by Kruthik111** [shivamyadavrgipt/Social_media_management#157]
![{BEF4BCD8-9DD7-490A-AA04-6A310964338E}](https://github.com/user-attachments/assets/6e7e5a5d-aa54-46e4-8e8d-f5a91f0cf4de)

**Comment by shivamyadavrgipt** [comment]
@Kruthik111 could you elaborate more how would you going to fix this it would be better for me.

**Comment by Kruthik111** [comment]
By adding a hamburger menu for small devices and a few more changes.

**Comment by shivamyadavrgipt** [comment]
@Kruthik111 assigned

**Comment by Kruthik111** [comment]
Thanks for assigning

**Comment by manikbhatt18** [comment]
i want to work on this issue

**Comment by Kruthik111** [comment]
> i want to work on this issue
@manikbhatt18 I have completed this already and sent a pulled request, you can check other issues.
