### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by shivamyadavrgipt** [shivamyadavrgipt/Social_media_management#178]
getting 404 error on clicking on dashboard
![{51670A8B-3C19-415E-BEE5-7944E973F12D}](https://github.com/user-attachments/assets/ea01605c-79fe-4251-b54a-061ea699cfc2)

**Comment by umarsayed12** [comment]
@shivamyadavrgipt Please assign me this issue!

**Comment by shivamyadavrgipt** [comment]
@umarsayed12 assigned

**Comment by umarsayed12** [comment]
@shivamyadavrgipt Please review the fixed issue.
