### ISSUE TITLE
Create a Custom 404 Page for Better User Experience

### ISSUE THREAD

**Issue by myselfshivams** [shivamyadavrgipt/Social_media_management#186]
Currently, when users encounter a broken or non-existent link, the website shows the default 404 error page. To enhance the user experience, we should create a custom 404 page with a user-friendly design and helpful navigation options (e.g., a link back to the homepage or other important sections). This will help guide users when they land on a missing page, improving overall usability.

Labels:
gssoc

@shivamyadavrgipt  Please assign this task to me (@myselfshivams).

**Comment by ScienHAC** [comment]
adding 404 page not found #186

**Comment by shivamyadavrgipt** [comment]
@myselfshivams assigned

**Comment by ScienHAC** [comment]
add custom notfoundpage.js checkout preview in pull request comment.
