### ISSUE TITLE
improve the footer

### ISSUE THREAD

**Issue by muskan-fatim** [shivamyadavrgipt/Social_media_management#207]
![image](https://github.com/user-attachments/assets/a2b0c757-20e3-4e1e-9459-e4a201a30e52)

i want to improve this css and give it new look

**Comment by muskan-fatim** [comment]
can you assign me this task

**Comment by shivamyadavrgipt** [comment]
@muskan-fatim assigned

**Comment by muskan-fatim** [comment]
![image](https://github.com/user-attachments/assets/6ae381f5-fde6-4500-9841-bae970f2363d)
see this tell me it look good or not or I have to need more improvement on it

**Comment by muskan-fatim** [comment]
I am waiting you reply

**Comment by shivamyadavrgipt** [comment]
@muskan-fatim good create a PR
