### ISSUE TITLE
Add FAQ section to Social Media Management Dashboard

### ISSUE THREAD

**Issue by ananyag309** [shivamyadavrgipt/Social_media_management#26]
To assist users with common questions and issues, a dedicated FAQ section should be added to the social media management dashboard. This will help improve user experience by providing quick answers and reducing the need for support inquiries.

**Comment by shivamyadavrgipt** [comment]
@ananyag309 i think you are telling to add to the footer path??

**Comment by ananyag309** [comment]
yes sure i will add there please add hacktoberfest and gssoc label

**Comment by shivamyadavrgipt** [comment]
@ananyag309 done kindly let me know when you will start working

**Comment by ananyag309** [comment]
@shivamyadavrgipt i will start from tomorrow itself
