### ISSUE TITLE
Frontend of dashboard

### ISSUE THREAD

**Issue by shivamyadavrgipt** [shivamyadavrgipt/Social_media_management#4]
We have to create a dashboard you can get inspiration from metricool website. which is also social media management website

**Comment by umesh-chilukuri** [comment]
i can create the dashboard for your application please assign me with this project

**Comment by shivamyadavrgipt** [comment]
please elaborate what you are gonna do

**Comment by umesh-chilukuri** [comment]
I actually always wanted to make this project ,
So actually  in the dashboard I want to show how many followers are present at each application like  twitter and Instagram and if possible we will also show in a graph type that how many subscribers ,follerwers are present

**Comment by Sharmaji513** [comment]
please assign me i will create this

**Comment by aligates2107** [comment]
Hi dear, I creating the frontend dashboard according to the social media management project, **Assign** to issue me.

**Comment by Sarthakkashyapp** [comment]
Hi @shivamyadavrgipt I would like to work on this issue.
