### ISSUE TITLE
automate deploying of project

### ISSUE THREAD

**Issue by shivamyadavrgipt** [shivamyadavrgipt/Social_media_management#50]
Project is already deployed you can get a link from repository.
the updates is not able to be seen on live link
ex:-
 this is from my local system
![{C250B811-32AC-4043-9709-675CECEF2247}](https://github.com/user-attachments/assets/f3a923c8-7bfe-486c-a3f0-33363f9206f0)

this is from the live link
here you can see  we are are able to see FAQ section which is  recently updated
![{3B3C9340-93C6-4C4D-8EB5-C485C8CB713E}](https://github.com/user-attachments/assets/bd524042-2e71-4c09-b5c8-0205e6d62ab8)

**Comment by Gauravtb2253** [comment]
i can work to automate the deployment
pls assign me

**Comment by shivamyadavrgipt** [comment]
@Gauravtb2253 assigned kindly inform me when you will start working

**Comment by Gauravtb2253** [comment]
> @Gauravtb2253 assigned kindly inform me when you will start working

Can you tell exactly what you need in automating
It will help me to start working on it

**Comment by shivamyadavrgipt** [comment]
@Gauravtb2253 as you can see in the second mage that is deployed we got url
but in first image it is the localhost server the new commits are seen on localhost but not on deployed link

**Comment by Gauravtb2253** [comment]
> @Gauravtb2253 as you can see in the second mage that is deployed we got url but in first image it is the localhost server the new commits are seen on localhost but not on deployed link

Actually in vercel, we need to check if there are some issue in deployment logs If so we need to solve them 
As per my knowledge vercel automatically triggers build of new commits directly so there shouldnt be any issue from that side
Can pls check once the logs

**Comment by shivamyadavrgipt** [comment]
@Gauravtb2253 you can deploy this on netlify and try later on I will add your link but currently the code has error its not running so once do check these
