### ISSUE TITLE
feat : Adding a Landing page with Description of this app

### ISSUE THREAD

**Issue by iamsaura8h** [shivamyadavrgipt/Social_media_management#58]
### hey @shivamyadavrgipt , 

i just went through the deployed link and i was directed to the dashboard directly. No home page or Landing page to tell about this project or anything at all.
So i would like to add **Landing Page or Home Page** which will have 
1) a suitable logo and name(if you want)
2) project description
3) about you, link to your other profiles 
4) link to this repo as " star this repository
5) a Explore now Button to reach the dashboard page.

comment down below if you want anything else to be added , i will be happy to take feedback

I will be more than happy to do this so please assign me this issue.
don't forget to add `gssoc-ext` and `hactoberfest-accepted` labels. 

thank you

**Comment by shivamyadavrgipt** [comment]
@iamsaura8h assigned kindly let me know when you will start working

**Comment by iamsaura8h** [comment]
> @iamsaura8h assigned kindly let me know when you will start working

I will start working on it tomorrow and it will be finished by tomorrow mid night
Thanks for assigning me this issue
