### ISSUE TITLE
Automated "Greetings" Workflow

### ISSUE THREAD

**Issue by samyak-aditya** [shivamyadavrgipt/Social_media_management#73]

**Comment by samyak-aditya** [comment]
Hey @shivamyadavrgipt please assign me label "level3" else my contribution won't be counted

**Comment by samyak-aditya** [comment]
Hey @shivamyadavrgipt add a level label to it

**Comment by shivamyadavrgipt** [comment]
@samyak-aditya added

**Comment by samyak-aditya** [comment]
Hey @shivamyadavrgipt Thanks 
I have raised the pr
