### ISSUE TITLE
link is not working

### ISSUE THREAD

**Issue by shivamyadavrgipt** [shivamyadavrgipt/Social_media_management#9]
page does not reload 
![{F79066F8-CF7D-4AE0-B5E8-EE2B996FECBA}](https://github.com/user-attachments/assets/756bede1-500e-4295-8279-1bfb1882b0ea)

**Comment by surajgoraicse** [comment]
Is it okay if I take this issue and work on a solution?

**Comment by surajgoraicse** [comment]
I got the solution.

https://github.com/user-attachments/assets/c8102681-85fc-40b6-b7be-8d7a9a245e01

**Comment by Devanshu1603** [comment]
please assign me this issue under gssoc ext level.

**Comment by shivamyadavrgipt** [comment]
@surajgoraicse brother i have checked issue is not fixed on clicking the link Not able to get the page

**Comment by surajgoraicse** [comment]
I have created a pull request.. @shivamyadavrgipt
