### ISSUE TITLE
Add Login/Signup Page to Enhance User Authentication

### ISSUE THREAD

**Issue by Lokesh-Bijarniya** [shivamyadavrgipt/Social_media_management#90]
### Description

# Overview:
We currently do not have a dedicated login/signup page, which is essential for user authentication and management. This issue aims to create a seamless experience for users to sign up and log in to their accounts.

# Proposed Changes:

**Login Page**:

- Allow users to enter their credentials (username/email and password).
- Implement a "remember me" feature for returning users.
- Add a "Forgot Password?" link to assist users in recovering their accounts.

**Signup Page**:

- Provide a form to collect necessary user information (username, email, password, confirm password).
- Validate inputs for security (e.g., email format, password strength).
- Include a checkbox for agreeing to terms and conditions.

**User Experience**:

- Ensure the pages are responsive and accessible on all devices.
- Provide feedback messages for successful or failed login/signup attempts.

**Benefits**:

-Streamlines the onboarding process for new users.
-Improves security by managing user authentication effectively.
-Enhances overall user experience by providing essential features for account management.

If you find this enhancement valuable, I would be more than happy to take ownership of this task and start implementing the changes right away. Please let me know if you have any questions or require further details. Thank you for considering this enhancement!

**Comment by Lokesh-Bijarniya** [comment]
@shivamyadavrgipt  Could you please assign this issue to me under gssoc-ext and hacktoberfest ?

**Comment by Balamurugan-cyber** [comment]
please assign me this issue

**Comment by shivamyadavrgipt** [comment]
@Lokesh-Bijarniya assigned

**Comment by Sourabh782** [comment]
@shivamyadavrgipt i see this issue unattended for about 2 weeks, if its free can i work on it??
